language: go
go:
- 1.5.3
- 1.6
matrix:
  allow_failures:
  - go: tip
sudo: false
install:
- go get -v ./...
- export PATH=${PATH}:${HOME}/gopath/bin
- curl https://bitbucket.org/birkenfeld/pygments-main/get/2.1.tar.gz -L -o 2.1.tar.gz
- mkdir -p ${HOME}/bin
- tar -xf 2.1.tar.gz
- mv birkenfeld-pygments-main-34530db252d3/* ${HOME}/bin
- rm -rf birkenfeld-pygments-main-34530db252d3
script:
- export PATH=${PATH}:${HOME}/bin
- make
- make docs
deploy:
  provider: gcs
  access_key_id: GOOGDIIIVPY7O6DG3PSZ
  secret_access_key:
    secure: Eh1b4GyDA8QHFZ0Kif/vkFdo6UnLWjKoofkMfBNjZwIiHxWosu1DFwwJY/XD8aEulyFAh+JdKYGGkn8zOYgZyOxqb913PfQs48RVOboNKNgizcSVM5TdLpPfID++3HOjzhjmEY/HFAdn1qeO3OC8fxYyh024UTK4w0mtdDCZwp7KPvCzPV/Rze1mtEIup1LiKvzK40LzdzBsM8g6mZbdFFcYn4ZZCx7qaiZ3uc1NS0b3BQyES5AItv0YfiDQiavNm5ExDfzo+f9P2vI9C7bf4O0b6i9tw/vACLCix7aPl34Jl1ipJBqpD16gohp9h3GHzv7/kmgtovmOlb70zFkeFhHTiBzHHE88frOKizTze1TSeHRRhWrklxMLeQH4JZzAiyd2rOgDzY2hUQFWHV+GDh8n9NyL8fM+S5/wI/FFVs1YktYFH/lGgTq3LHyBncy2bv3h8hua2h5Ik2tMrbBV5E9pRRpJiTCLc7xpJK4MUkV0WeWNuhDel6uFcJdPP4hrwziPsI6nUAa8lcMNCu0kGKmX3QskyAj1V3QnuTs1lQyNpIwTdVPI+krftii8EYGJdGqmKQyQzmyHHCxbDW9SRMHuNajxIUfKTDdVUC0lh6WTx2Kld99iSItwDGOvrTuyRtc5xWJ374kEAHxoLT11jJd7QjVa83ARE8mFxXFdpH0=
  bucket: goa.design
  local-dir: public/reference
  upload-dir: reference
  skip-cleanup: true
  acl: public-read
  cache-control: max-age=300
  on:
    repo: goadesign/logging
    go: '1.5.3'
